server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1997
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # or validate, create, none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect


